### PR TITLE
add buble, babel options to register

### PR DESCRIPTION
**Pull request by ezekielchentnik**
PR for issue #22

### CODE REVIEW

**Comment by TylorS** [comment]
This looks good to me, but I think it'd be preferable if we could drop the lodash depedency. A `deepmerge` function could look something like

``` js
function merge (target, src) {
  const isArray = Array.isArray(src)
  let destination = target || isArray ? [] : {}

  if (isArray) {
    target = target || []

    destination = target.concat(destination)

    src.forEach((e, i) => {
      if (destination[i] === void 0) {
        destination[i] = e
      } else if (typeof e === 'object') {
        destination[i] = merge(target[i], e)
      } else {
        if (target.indexOf(e) === -1) {
          destination.push(e)
        }
      }
    })
  } else {
    if (typeof target === 'object') {
      Object.keys(target).forEach(key => {
        destination[key] = target[key]
      })
    }

    Object.keys(src).forEach(key => {
      if (typeof src[key] !== object) {
        destination[key] = src[key]
      } else {
        if (!target[key]) {
          destination[key] = src[key]
        } else {
          destination[key] = merge(target[key], src[key])
        }
      }
    })
  }

  return destination
}
```

**Comment by ezekielchentnik** [comment]
@TylorS agreed, less deps.  Just made commit to reflect these changes.

**Comment by TylorS** [comment]
LGTM but @davidchase gets the final say :+1:

**Comment by davidchase** [comment]
@ezekielchentnik thanks for the PR

**Review by davidchase — CHANGES_REQUESTED** [review]
@ezekielchentnik thanks for the PR

small note if its possible i would like to move the merge to a separate file in order to keep the the register simple.

i think after that its good to merge, probably going to put some unit tests around the `deepMerge` at some point

**Comment by ezekielchentnik** [comment]
@davidchase extracted merge into a separate file.  put it in the root dir, I guess at a later point if there are more helpers etc, it could go in a /lib or /src  but for now, requested changes are there and should be good to go.

**Review by davidchase — APPROVED** [review]

**Pull request merged**
